UoW.WEB/Controllers/BayiUrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using UoW.ADMIN.Helpers;
using UoW.CORE.Interface;
using UoW.DOMAIN.Models;
using UoW.LOG.Models;
using X.PagedList;

namespace UoW.WEB.Controllers
{
    public class BayiUrunController : Controller
    {

        #region Fields

        private readonly IUnitOfWork<Bayi> _unitOfWorkBayi;
        private readonly IUnitOfWork<Kullanici> _unitOfWorkAdmin;
        private readonly IUnitOfWork<Urun> _unitOfWorkUrun;
        private readonly IUnitOfWork<UrunResimler> _unitOfWorkUrunResimler;
        private readonly IUnitOfWork<Kategori> _unitOfWorkKategori;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly IUnitOfWork<Marka> _unitofWorkMarka;
        private readonly IUnitOfWork<UrunFiyat> _unitOfWorkUrunFiyat;
        private readonly IUnitOfWork<MusteriGrupOzelUrun> _unitOfWorkMusteriOzelUrun;
        private readonly IUnitOfWork<MusteriGrubu> _unitOfWorkMusteriGrubu;
        private readonly IUnitOfWork<Etiketler> _unitOfWorkEtiketler;
        private readonly IUnitOfWork<EtiketGonderi> _unitOfWorkEtiketUrunler;
        private readonly IUnitOfWork<StokBirimi> _unitOfWorkStokBirimi;
        private readonly IUnitOfWorkLog<Durumlar> _unitOfWorkLogDurumlar;
        private readonly IUnitOfWorkLog<Islemler> _unitOfWorkLogIslemler;
        private readonly IUnitOfWorkLog<Loglar> _unitOfWorkLogLoglar;
        private readonly IUnitOfWorkLog<Yonetici> _unitofWorkLogYonetici;
        private readonly IUnitOfWork<UrunStok> _unitOfWorkStoktakiler;
        private readonly IUnitOfWork<Begeni> _unitOfWorkBegeni;
        private readonly IUnitOfWork<UstListe> _unitOfWorkUstList;
        private readonly IUnitOfWork<Liste> _unitOfWorkListe;
        private readonly IUnitOfWork<StokBildirim> _unitOfWorkStokBildirim;
        private readonly IUnitOfWork<SiteInfo> _unitOfWorkSiteInfo;
        private readonly IUnitOfWork<Haber> _unitOfWorkHaber;
        private readonly IUnitOfWork<Sepet> _unitOfWorkSepetler;
        private readonly IUnitOfWork<UrunRenk> _unitOfWorkUrunRenkler;
        private readonly IConfiguration _configuration;

        private readonly int? page;
        private readonly int? markaPage;

        public BayiUrunController(IUnitOfWork<Bayi> unitOfWorkBayi,
            IUnitOfWork<Kullanici> unitOfWorkAdmin,
            IUnitOfWork<Urun> unitOfWorkUrun,
            IUnitOfWork<UrunResimler> unitOfWorkUrunResimler,
            IUnitOfWork<Kategori> unitOfWorkKategori,
            IUnitOfWork<Marka> unitOfWorkMarka,
            IUnitOfWork<UrunFiyat> unitOfWorkUrunFiyat,
            IUnitOfWork<MusteriGrupOzelUrun> unitOfWorkMusteriOzelUrun,
            IUnitOfWork<MusteriGrubu> unitOfWorkMusteriGrubu,
            IUnitOfWork<Etiketler> unitOfWorkEtiketler,
            IUnitOfWork<EtiketGonderi> unitOfWorkEtiketUrunler,
            IUnitOfWork<StokBirimi> unitOfWorkStokBirimi,
            IWebHostEnvironment hostEnvironment,
            IUnitOfWorkLog<Durumlar> unitOfWorkLogDurumlar,
            IUnitOfWorkLog<Islemler> unitOfWorkLogIslemler,
            IUnitOfWorkLog<Loglar> unitOfWorkLogLoglar,
            IUnitOfWorkLog<Yonetici> unitofWorkLogYonetici,
            IConfiguration configuration,
            IUnitOfWork<UrunStok> unitOfWorkStoktakiler,
            IUnitOfWork<Begeni> unitOfWOrkBegeni,
            IUnitOfWork<Liste> unitOfWorkListe,
            IUnitOfWork<UstListe> unitOfWorkUstList,
            IUnitOfWork<StokBildirim> unitOfWorkStokBildirim,
            IUnitOfWork<Begeni> unitOfWorkBegeni,
            IUnitOfWork<Haber> unitOfWorkHaber,
            IUnitOfWork<SiteInfo> unitOfWorkSiteInfo,
            IUnitOfWork<Sepet> unitOfWorkSepetler,
            IUnitOfWork<UrunRenk> unitOfWorkUrunRenkler)
        {
            this._unitOfWorkBayi = unitOfWorkBayi;
            this._unitOfWorkAdmin = unitOfWorkAdmin;
            this._unitOfWorkUrun = unitOfWorkUrun;
            this._unitOfWorkKategori = unitOfWorkKategori;
            this._unitOfWorkUrunResimler = unitOfWorkUrunResimler;
            this._hostEnvironment = hostEnvironment;
            this._unitofWorkMarka = unitOfWorkMarka;
            this._unitOfWorkUrunFiyat = unitOfWorkUrunFiyat;
            this._unitOfWorkMusteriGrubu = unitOfWorkMusteriGrubu;
            this._unitOfWorkMusteriOzelUrun = unitOfWorkMusteriOzelUrun;
            this._unitOfWorkEtiketler = unitOfWorkEtiketler;
            this._unitOfWorkEtiketUrunler = unitOfWorkEtiketUrunler;
            this._unitOfWorkStokBirimi = unitOfWorkStokBirimi;
            this._configuration = configuration;
            this._unitOfWorkLogDurumlar = unitOfWorkLogDurumlar;
            this._unitOfWorkLogIslemler = unitOfWorkLogIslemler;
            this._unitOfWorkLogLoglar = unitOfWorkLogLoglar;
            this._unitofWorkLogYonetici = unitofWorkLogYonetici;
            this._unitOfWorkStoktakiler = unitOfWorkStoktakiler;
            this._unitOfWorkBegeni = unitOfWOrkBegeni;
            this._unitOfWorkUstList = unitOfWorkUstList;
            this._unitOfWorkListe = unitOfWorkListe;
            this._unitOfWorkBegeni = unitOfWorkBegeni;
            this._unitOfWorkStokBildirim = unitOfWorkStokBildirim;
            this._unitOfWorkHaber = unitOfWorkHaber;
            this._unitOfWorkSiteInfo = unitOfWorkSiteInfo;
            this._unitOfWorkSepetler = unitOfWorkSepetler;
            this._unitOfWorkUrunRenkler = unitOfWorkUrunRenkler;
        }

        #endregion

        [CheckOtherLogin]
        [HttpGet, ActionName("ListProductSpecialBayi")]
        public async Task<IActionResult> ListProductSpecialBayi(int? page)
        {
            int id = Convert.ToInt32(HttpContext.Session.GetInt32("IdB"));

            Bayi gelenBayi = await _unitOfWorkBayi.Repository.Where(x => x.ID == id).Include("musteriGrubu").FirstOrDefaultAsync();

            var pageNumber = page ?? 1;
            ViewBag.Urunler = _unitOfWorkMusteriOzelUrun.Repository.Where(x => x.MusteriGrupID == gelenBayi.musteriGrubu.ID)
               .Include("urunOzelUrun")
               .Include("urunOzelUrun.kategori")
               .Include("urunOzelUrun.marka")
               .Include("urunOzelUrun.kullanici")
               .ToPagedList(pageNumber, 24);

            List<Urun> urunNo = (List<Urun>)await _unitOfWorkUrun.Repository.All();
            ViewBag.UrunNo = new SelectList(urunNo, "ID", "UrunNo");

            //await CreateModeratorLog("Başarılı", "Listeleme", "ListProduct", "Urun");
            return View();
        }

        [CheckOtherLogin]
        [HttpGet, ActionName("AllProductList")]
        public async Task<IActionResult> AllProductList(int? page)
        {

            var pageNumber = page ?? 1;
            ViewBag.Urunler = _unitOfWorkUrun.Repository
               .Where(x => x.ID > 0 && x.UstUrunID == 0)
               .Include("kategori")
               .Include("kullanici")
               .Include("marka")
               .Include("stokbirimi")
               .ToPagedList(pageNumber, 24);

            List<Urun> urunNo = (List<Urun>)await _unitOfWorkUrun.Repository.All();
            ViewBag.UrunNo = new SelectList(urunNo, "ID", "UrunNo");

            //await CreateModeratorLog("Başarılı", "Listeleme", "ListProduct", "Urun");
            return View();
        }

        [HttpGet]
        public IActionResult DetailPartialProductPrice()
        {

            return PartialView("DetailPartialProductPrice");
        }

        [CheckOtherLogin]
        public async Task<IActionResult> DetailProduct(int Id)
        {

            int IdBayi = Convert.ToInt32(HttpContext.Session.GetInt32("IdB"));
            Bayi bayi = await _unitOfWorkBayi.Repository.Where(x => x.ID == IdBayi).Include("musteriGrubu").FirstOrDefaultAsync();
            ViewBag.Bayi = bayi;

            StokBildirim bildirimVarmi = await _unitOfWorkStokBildirim.Repository.Where(x => x.UrunId == Id && x.BayiId == IdBayi && x.Durum == CORE.Enums.StokBildirimDurum.BildirimYapildi).FirstOrDefaultAsync();

            if (bildirimVarmi != null)
            {
                bildirimVarmi.Durum = CORE.Enums.StokBildirimDurum.Okundu;
                _unitOfWorkStokBildirim.Repository.Update(bildirimVarmi);
                _unitOfWorkStokBildirim.Repository.Save();
            }

            Urun u = await _unitOfWorkUrun.Repository.Where(x => x.ID == Id).Include("kategori").Include("marka").Include("stokbirimi").SingleAsync();

            List<UrunRenk> urunRenks = await _unitOfWorkUrunRenkler.Repository.Where(x => x.UrunID == Id).Include("renk").ToListAsync();
            ViewBag.UrunRenkler = urunRenks;

            List<UrunResimler> uResimlers = await _unitOfWorkUrunResimler.Repository.Where(x => x.UrunID == u.ID).ToListAsync();
            ViewBag.UrunResimler = uResimlers;

            List<UrunFiyat> uFiyatlars = await _unitOfWorkUrunFiyat.Repository.Where(x => x.UrunID == Id).ToListAsync();
            ViewBag.UrunFiyat = uFiyatlars;

            List<Urun> altUrunler = await _unitOfWorkUrun.Repository.Where(x => x.UstUrunID == u.ID).ToListAsync();
            ViewBag.AltUrunler = altUrunler;

            List<EtiketGonderi> etiketler = await _unitOfWorkEtiketUrunler.Repository.Where(x => x.GonderiID == u.ID).Include("etiketler").ToListAsync();
            ViewBag.Etiketler = etiketler;

            List<Begeni> begeniler = await _unitOfWorkBegeni.Repository.Where(x => x.ID > 0).ToListAsync();

            List<Urun> urunler = ViewBag.Urunler;

            foreach (var item in begeniler)
            {
                if (item.UrunID == u.ID)
                {
                    TempData["Disable"] = true;
                }

UoW.WEB/Views/BayiUrun/AllProductList.cshtml
@using UoW.DOMAIN.Models
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@using X.PagedList.Mvc.Core.Common;

@section Styles{
    <style>
        .page-link {
            position: relative;
            display: block;
            padding: .5rem .75rem;
            margin-left: -1px;
            line-height: 1.25;
            color: #fff;
            background-color: #34509d;
            border: 1px solid #34509d;
        }

            .page-link a {
                color: #fff;
            }

                .page-link a:hover {
                    color: #34509d;
                }
    </style>
}

@{
    ViewData["Title"] = "ListProduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int id = Convert.ToInt32(TempData["Id"]);
    int indirimOran = 0;
}

<div class="container-fluid">
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h4 class="mb-0 font-size-18">ÜRÜN MARKETİ</h4>

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                @foreach (var item in ViewBag.Urunler)
                {
                    <div class="col-xl-3 col-sm-6">
                        <div class="card">
                            <div class="card-body">
                                <div class="product-img position-relative">
                                    @if (item.IndirimOrani > 0)
                                    {
                                        indirimOran = Convert.ToInt32(item.IndirimOrani);
                                        <div class="avatar-sm product-ribbon">
                                            <span class="avatar-title rounded-circle bg-primary">
                                                - @indirimOran %
                                            </span>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="avatar-sm product-ribbon">

                                        </div>
                                    }
                                    <img src="https://admin.kiracelektrik.com.tr/files/uploads/urun/@item.Resim" alt="" class="img-fluid mx-auto d-block">
                                </div>
                                <div class="mt-4 text-center">
                                    <h5 class="mb-3 text-truncate">
                                        <a href="@Url.Action("DetailProduct","BayiUrun", new { Id = item.ID })"
                                           class="text-dark">@item.UrunAdi </a>
                                    </h5>
                                    @if (item.IndirimOrani > 0)
                                    {
                                        <h5 class="my-0"><span class="text-muted mr-2"><del>@string.Format("{0:c}", item.KDVFiyat)</del></span> <b>@string.Format("{0:C}", item.IndirimliFiyat)</b></h5>
                                    }
                                    else
                                    {
                                        <h5 class="my-0"><span class="text-muted mr-2">@string.Format("{0:c}", item.KDVFiyat)</span></h5>
                                    }

                                </div>

                            </div>
                            <div class="form-group" style="padding:10px;">
                                @if (item.ID == id)
                                {
                                    <a href="#" class="btn btn-sm btn-block btn-info">Sepete Eklendi</a>

                                }
                                else
                                {
                                    <a href="@Url.Action("SepetListEkle","Siparis", new { Id = item.ID })" class="btn btn-sm btn-block btn-success">Sepete Ekle</a>
                                }

                            </div>
                        </div>
                    </div>
                }

            </div>
            <!-- end row -->
            <div class="row">
                <div class="col-lg-12">
                    @Html.PagedListPager((IPagedList<Urun>)ViewBag.Urunler,
                   page => Url.Action("AllProductList", new { page }),
                   PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new PagedListRenderOptions
                   {
                            MaximumPageNumbersToDisplay = 10,
                       DisplayPageCountAndCurrentLocation = true,
                       UlElementClasses = new[] { "pagination pagination-rounded justify-content-center mt-4" },
                       LiElementClasses = new[] { "page-link" },
                       EllipsesFormat = "&#8230;",
                       DisplayLinkToIndividualPages = true,
                       ActiveLiElementClass = "page-item",
                       DisplayLinkToFirstPage = X.PagedList.Web.Common.PagedListDisplayMode.IfNeeded,
                       DisplayLinkToLastPage = X.PagedList.Web.Common.PagedListDisplayMode.IfNeeded,
                       DisplayLinkToPreviousPage = X.PagedList.Web.Common.PagedListDisplayMode.IfNeeded,
                       DisplayLinkToNextPage = X.PagedList.Web.Common.PagedListDisplayMode.IfNeeded,
                       PageCountAndCurrentLocationFormat = "",
                       ContainerDivClasses = new[] { "pagination-container" }
                        },
                    new AjaxOptions() { HttpMethod = "GET" }))
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts
    {
    <script src="https://admin.kiracelektrik.com.tr/files/assets/libs/select2/js/select2.min.js"></script>
    <script src="https://admin.kiracelektrik.com.tr/files/assets/js/pages/ecommerce-select2.init.js"></script>
    <script src="https://admin.kiracelektrik.com.tr/files/assets/libs/bs-custom-file-input/bs-custom-file-input.min.js"></script>
    <script src="https://admin.kiracelektrik.com.tr/files/assets/js/pages/form-element.init.js"></script>

    <script type="text/javascript">


        $(document).ready(function () {
            $('#dropdown1').select2();
        });

    </script>
}

UoW.WEB/Views/BayiUrun/ListParentList.cshtml
@model IEnumerable<UoW.DOMAIN.Models.UstListe>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<table class="table table-condensed">
    <tbody>
        @foreach (var item in Model) { 
            <tr>
                <td><a href="@Url.Action("ListToSubList","BayiUrun", new { ID = item.ID })" class="btn btn-link">@item.ListeAdi</a></td>
            </tr>
        }
    </tbody>
</table>

UoW.WEB/Views/BayiUrun/ListParentLists.cshtml
@model IEnumerable<UoW.DOMAIN.Models.UstListe>
@{
    ViewData["Title"] = "ListSubItems";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">

                    </div>
                    <div class="card-body">
                        <table class="table table-condensed">
                            <thead>
                                <tr>
                                    <td>#</td>
                                    <td>Liste Adı</td>                                  
                                    <td>Eklenme Tarih</td>
                                    <td>Güncellenme Tarih</td>
                                    <td>Bayi</td>
                                    <td>İşlem</td>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.ID</td>
                                        <td>@item.ListeAdi</td>                                      
                                        <td>@item.EklenmeTarih.ToShortDateString() @item.EklenmeTarih.ToShortTimeString()</td>
                                        <td>@item.GuncellenmeTarih.ToShortDateString() @item.GuncellenmeTarih.ToShortTimeString()</td>
                                        <td>@item.bayiListUst.BayiAdi</td>
                                        <td><a href="@Url.Action("ListSubItems","BayiUrun", new { ID= item.ID })" class="btn btn-sm btn-danger">Kaldır</a></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

UoW.WEB/Views/BayiUrun/ListProductLikes.cshtml
@using UoW.DOMAIN.Models
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@using X.PagedList.Mvc.Core.Common;

@section Styles{
    <style>
        .page-link {
            position: relative;
            display: block;
            padding: .5rem .75rem;
            margin-left: -1px;
            line-height: 1.25;
            color: #fff;
            background-color: #34509d;
            border: 1px solid #34509d;
        }

            .page-link a {
                color: #fff;
            }

                .page-link a:hover {
                    color: #34509d;
                }
    </style>
}

@{
    ViewData["Title"] = "ListProduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int id = Convert.ToInt32(TempData["Id"]);
    int indirimOran = 0;
    IPagedList<Begeni> begeniler = ViewBag.BegeniList as IPagedList<Begeni>;
}

    <div class="container-fluid">
        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-flex align-items-center justify-content-between">
                    <h4 class="mb-0 font-size-18">İLGİLENDİĞİM ÜRÜNLER</h4>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="row">
                    <div class="col-xl-12 col-sm-12">
                        <div class="card">
                            <div class="card-body">
                                <table class="table table-condensed">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Ürün No</th>
                                            <th>Ürün Adı</th>
                                            <th>Fiyat</th>
                                            <th>İşlem</th>                    
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in begeniler)
                                        {
                                        <tr>
                                           
                                            <td><img src="https://admin.kiracelektrik.com.tr/files/uploads/urun/@item.urunBegeni.Resim" width="50" height="50" class="img img-thumbnail" /></td>
                                            <td>@item.urunBegeni.UrunNo</td>
                                            <td><a href="@Url.Action("DetailProduct","BayiUrun", new { ID =item.urunBegeni.ID })">@item.urunBegeni.UrunAdi</a></td>
                                            @if (item.urunBegeni.IndirimOrani > 0)
                                            {
                                                <td><span class="text-muted"><del>@item.urunBegeni.KDVFiyat</del></span> <b class="text-success">@item.urunBegeni.IndirimliFiyat</b></td>
                                            }
                                            else
                                            {
                                                <td>@item.urunBegeni.KDVFiyat</td>
                                            }
                                           
                                            <td>
                                                <a href="@Url.Action("DissLikeHomePageList","BayiUrun", new { ID = item.urunBegeni.ID })" data-toggle="tooltip" data-placement="top" title="" data-original-title="Favorilerden Çıkar"><img src="~/Files/Bayi/icon_star_full.png" /></a>
                                            </td>
                                        </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end row -->
                <div class="row">
                    <div class="col-lg-12">
                        @Html.PagedListPager((IPagedList<Begeni>)ViewBag.BegeniList,
                       page => Url.Action("ListProductLikes", new { page }),
                       PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new PagedListRenderOptions
                       {
                                MaximumPageNumbersToDisplay = 10,
                           DisplayPageCountAndCurrentLocation = true,
                           UlElementClasses = new[] { "pagination pagination-rounded justify-content-center mt-4" },
                           LiElementClasses = new[] { "page-link" },
                           EllipsesFormat = "&#8230;",
                           DisplayLinkToIndividualPages = true,
                           ActiveLiElementClass = "page-item",
                           DisplayLinkToFirstPage = X.PagedList.Web.Common.PagedListDisplayMode.IfNeeded,
                           DisplayLinkToLastPage = X.PagedList.Web.Common.PagedListDisplayMode.IfNeeded,
                           DisplayLinkToPreviousPage = X.PagedList.Web.Common.PagedListDisplayMode.IfNeeded,
                           DisplayLinkToNextPage = X.PagedList.Web.Common.PagedListDisplayMode.IfNeeded,
                           PageCountAndCurrentLocationFormat = "",
                           ContainerDivClasses = new[] { "pagination-container" }
                            },
                        new AjaxOptions() { HttpMethod = "GET" }))
                    </div>
                </div>
            </div>
        </div>
    </div>

UoW.WEB/Views/BayiUrun/ListProductSpecialBayi.cshtml
@using UoW.DOMAIN.Models
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@using X.PagedList.Mvc.Core.Common;

@section Styles{
    <style>
        .page-link {
            position: relative;
            display: block;
            padding: .5rem .75rem;
            margin-left: -1px;
            line-height: 1.25;
            color: #fff;
            background-color: #34509d;
            border: 1px solid #34509d;
        }

            .page-link a {
                color: #fff;
            }

                .page-link a:hover {
                    color: #34509d;
                }
    </style>
}

@{
    ViewData["Title"] = "ListProduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int indirimOran = 0;
}

    <div class="container-fluid">
        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-flex align-items-center justify-content-between">
                    <h4 class="mb-0 font-size-18">BAYİYE ÖZEL ÜRÜNLER</h4>

                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="row">
                    @foreach (var item in ViewBag.Urunler)
                    {
                        <div class="col-xl-3 col-sm-6">
                            <div class="card">
                                <div class="card-body">
                                    <div class="product-img position-relative">
                                        @if (item.urunOzelUrun.IndirimOrani > 0)
                                        {
                                            indirimOran = Convert.ToInt32(item.urunOzelUrun.IndirimOrani);
                                            <div class="avatar-sm product-ribbon">
                                                <span class="avatar-title rounded-circle  bg-primary">
                                                    - @indirimOran %
                                                </span>
                                            </div>
                                        }
                                        else
                                        {
                                            <div class="avatar-sm product-ribbon">

                                            </div>
                                        }
                                        <img src="https://admin.kiracelektrik.com.tr/files/uploads/urun/@item.urunOzelUrun.Resim" alt="" class="img-fluid mx-auto d-block">
                                    </div>
                                    <div class="mt-4 text-center">
                                        <h5 class="mb-3 text-truncate">
                                            <a href="@Url.Action("DetailProduct","BayiUrun", new { Id = item.urunOzelUrun.ID })"
                                               class="text-dark">@item.urunOzelUrun.UrunAdi </a>
                                        </h5>
                                        @if (item.urunOzelUrun.IndirimOrani > 0)
                                        {
                                            <h5 class="my-0"><span class="text-muted mr-2"><del>@string.Format("{0:c}", item.urunOzelUrun.KDVFiyat)</del></span> <b>@string.Format("{0:C}", item.urunOzelUrun.IndirimliFiyat)</b></h5>
                                        }
                                        else
                                        {
                                            <h5 class="my-0"><span class="text-muted mr-2">@string.Format("{0:c}", item.urunOzelUrun.KDVFiyat)</span></h5>
                                        }

                                    </div>

                                </div>
                                <div class="form-group" style="padding:10px;">
                                    <a href="@Url.Action("DetailProduct","BayiUrun", new { Id = item.urunOzelUrun.ID })" class="btn btn-sm btn-block btn-success">Detay</a>
                                </div>
                            </div>
                        </div>
                    }

                </div>
                <!-- end row -->
                <div class="row">
                    <div class="col-lg-12">
                        @Html.PagedListPager((IPagedList<MusteriGrupOzelUrun>)ViewBag.Urunler,
                       page => Url.Action("ListProductSpecialBayi", new { page }),
                       PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new PagedListRenderOptions
                       {
                                MaximumPageNumbersToDisplay = 10,
                           DisplayPageCountAndCurrentLocation = true,
                           UlElementClasses = new[] { "pagination pagination-rounded justify-content-center mt-4" },
                           LiElementClasses = new[] { "page-link" },
                           EllipsesFormat = "&#8230;",
                           DisplayLinkToIndividualPages = true,
                           ActiveLiElementClass = "page-item",
                           DisplayLinkToFirstPage = X.PagedList.Web.Common.PagedListDisplayMode.IfNeeded,
                           DisplayLinkToLastPage = X.PagedList.Web.Common.PagedListDisplayMode.IfNeeded,
                           DisplayLinkToPreviousPage = X.PagedList.Web.Common.PagedListDisplayMode.IfNeeded,
                           DisplayLinkToNextPage = X.PagedList.Web.Common.PagedListDisplayMode.IfNeeded,
                           PageCountAndCurrentLocationFormat = "",
                           ContainerDivClasses = new[] { "pagination-container" }
                            },
                        new AjaxOptions() { HttpMethod = "GET" }))
                    </div>
                </div>
            </div>
        </div>
    </div>

@section scripts
    {
    <script src="https://admin.kiracelektrik.com.tr/files/assets/libs/select2/js/select2.min.js"></script>
    <script src="https://admin.kiracelektrik.com.tr/files/assets/js/pages/ecommerce-select2.init.js"></script>
    <script src="https://admin.kiracelektrik.com.tr/files/assets/libs/bs-custom-file-input/bs-custom-file-input.min.js"></script>
    <script src="https://admin.kiracelektrik.com.tr/files/assets/js/pages/form-element.init.js"></script>

    <script type="text/javascript">


        $(document).ready(function () {
            $('#dropdown1').select2();
        });

    </script>
}

UoW.WEB/Views/BayiUrun/ProductComparison.cshtml
@{
    ViewData["Title"] = "ProductComparison";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <h4>Ürün Karşılaştırma</h4>
</div>